#include "rules/rules.hpp"
#include "core/net.hpp"
#include "core/strings.hpp"
#include <algorithm>
#include <stdexcept>
#include <sstream>
namespace guardsight::rules {
using namespace guardsight::core;
bool PortSpec::contains(uint16_t p) const{return any||(p>=first&&p<=last);} std::string PortSpec::str() const{if(any)return "any"; if(first==last)return std::to_string(first); return std::to_string(first)+":"+std::to_string(last);} static PortSpec parse_port(const std::string& s,Diagnostics& d,std::size_t line){auto v=trim(s); if(v=="any")return {}; auto pos=v.find(':'); try{if(pos==std::string::npos){int p=std::stoi(v); if(p<0||p>65535)throw std::out_of_range("port"); return {false,uint16_t(p),uint16_t(p)};} std::string a=v.substr(0,pos),b=v.substr(pos+1); int lo=a.empty()?0:std::stoi(a),hi=b.empty()?65535:std::stoi(b); if(lo<0||hi>65535||lo>hi)throw std::out_of_range("range"); return {false,uint16_t(lo),uint16_t(hi)};}catch(...){d.warn("rule.port","invalid port expression",line); return {};}}
static std::vector<std::string> lex_header(const std::string& h){std::vector<std::string> out; std::string cur; bool bracket=false; for(char c:h){if(c=='[')bracket=true; if(c==']')bracket=false; if(std::isspace((unsigned char)c)&&!bracket){if(!cur.empty()){out.push_back(cur);cur.clear();}}else cur.push_back(c);} if(!cur.empty())out.push_back(cur); return out;} static std::map<std::string,std::vector<std::string>> parse_options(const std::string& body){std::map<std::string,std::vector<std::string>> opt; std::string cur; bool q=false; std::vector<std::string> parts; for(char c:body){if(c=='"')q=!q; if(c==';'&&!q){parts.push_back(cur);cur.clear();}else cur.push_back(c);} if(!trim(cur).empty())parts.push_back(cur); for(auto& p:parts){auto pos=p.find(':'); std::string k=lower(trim(pos==std::string::npos?p:p.substr(0,pos))); std::string v=pos==std::string::npos?"":strip_quotes(trim(p.substr(pos+1))); if(!k.empty())opt[k].push_back(v);} return opt;}
Result<std::vector<Rule>> parse_rules_text(const std::string& text){Diagnostics d; std::vector<Rule> rules; auto lines=split_lines(text); for(std::size_t i=0;i<lines.size();++i){std::string line=trim(remove_comment(lines[i])); if(line.empty())continue; auto lp=line.find('('),rp=line.rfind(')'); if(lp==std::string::npos||rp==std::string::npos||rp<lp){d.warn("rule.syntax","rule lacks option block",i+1); continue;} auto toks=lex_header(trim(line.substr(0,lp))); if(toks.size()<7){d.warn("rule.header","rule header has fewer than seven fields",i+1); continue;} Rule r; r.action=lower(toks[0]); r.protocol=lower(toks[1]); r.source=toks[2]; r.source_port=parse_port(toks[3],d,i+1); r.direction=toks[4]; r.destination=toks[5]; r.destination_port=parse_port(toks[6],d,i+1); r.options=parse_options(line.substr(lp+1,rp-lp-1)); auto problems=validate_rule(r); for(auto& p:problems)d.warn("rule.validation",p,i+1); r.normalized=normalize_rule(r); rules.push_back(r);} return {rules,d};}
std::vector<std::string> validate_rule(const Rule& r){std::vector<std::string> v; static const std::vector<std::string> actions={"alert","pass","drop","reject","log"}; if(std::find(actions.begin(),actions.end(),r.action)==actions.end())v.push_back("unknown action "+r.action); if(r.protocol!="tcp"&&r.protocol!="udp"&&r.protocol!="icmp"&&r.protocol!="ip")v.push_back("unknown protocol "+r.protocol); if(r.direction!="->"&&r.direction!="<>"&&r.direction!="<-" )v.push_back("unusual direction "+r.direction); if(!r.options.count("sid"))v.push_back("missing sid option"); if(!r.options.count("msg"))v.push_back("missing msg option"); if(r.options.count("sid")&&!is_decimal(r.options.at("sid").front()))v.push_back("sid is not numeric"); return v;} std::string normalize_rule(const Rule& r){std::ostringstream o; o<<r.action<<' '<<r.protocol<<' '<<r.source<<' '<<r.source_port.str()<<' '<<r.direction<<' '<<r.destination<<' '<<r.destination_port.str()<<" ("; bool first=true; for(auto& kv:r.options){for(auto& v:kv.second){if(!first)o<<"; "; first=false; o<<kv.first; if(!v.empty())o<<":\""<<v<<"\"";}} o<<";)"; return o.str();}
static bool addr_match(const std::string& spec,const std::optional<IPv4Address>& ip){auto s=lower(spec); if(s=="any"||s==""||s=="")return true; if(!ip)return false; auto c=parse_cidr(spec); return c?c->contains(*ip):ip->str()==spec;} std::vector<RuleMatch> match_rules(const std::vector<Rule>& rules,const std::vector<packet::PacketMetadata>& packets){std::vector<RuleMatch> out; for(auto& p:packets){for(auto& r:rules){if(r.protocol!="ip"&&r.protocol!=p.protocol)continue; if(!addr_match(r.source,p.src_ip)||!addr_match(r.destination,p.dst_ip))continue; if(!r.source_port.contains(p.src_port)||!r.destination_port.contains(p.dst_port))continue; out.push_back({r,p.summary()});}} return out;} std::string summarize_rules(const std::vector<Rule>& rules){std::map<std::string,int> actions,protocols; for(auto& r:rules){actions[r.action]++; protocols[r.protocol]++;} std::ostringstream o; o<<"rules="<<rules.size(); for(auto& a:actions)o<<" action."<<a.first<<"="<<a.second; for(auto& p:protocols)o<<" proto."<<p.first<<"="<<p.second; return o.str();}
}
