#include "ioc/ioc.hpp"
#include "core/strings.hpp"
#include <algorithm>
#include <map>
#include <sstream>
namespace guardsight::ioc {
using namespace guardsight::core;
std::string ioc_type_name(IocType t){switch(t){case IocType::ip:return "ip";case IocType::cidr:return "cidr";case IocType::domain:return "domain";case IocType::url:return "url";case IocType::hash:return "hash";default:return "unknown";}}
static std::map<std::string,std::string> fields_from_line(const std::string& line){auto comma=parse_key_value_list(line,',','='); auto semi=parse_key_value_list(line,';','='); if(semi.size()>comma.size())return semi; return comma;}
IocEntry normalize_ioc_line(const std::string& line,Diagnostics& d,std::size_t line_no){std::string clean=trim(remove_comment(line)); IocEntry e; e.raw=line; if(clean.empty())return e; auto fields=fields_from_line(clean); std::string token=clean; auto it=fields.find("value"); if(it!=fields.end())token=it->second; else {auto parts=split(clean,','); if(!parts.empty())token=trim(parts[0]);} if(fields.count("severity"))e.severity=lower(fields["severity"]); if(fields.count("confidence")){try{e.confidence=std::stod(fields["confidence"]);}catch(...){d.warn("ioc.confidence","invalid confidence",line_no);}} if(fields.count("list"))e.allow=lower(fields["list"])=="allow"||lower(fields["list"])=="allowlist"; if(fields.count("source"))e.source=fields["source"]; token=strip_quotes(trim(token)); auto cidr=parse_cidr(token); if(token.find('/')!=std::string::npos&&cidr){e.type=IocType::cidr; e.value=cidr->str(); return e;} auto ip=parse_ipv4(token); if(ip){e.type=IocType::ip; e.value=ip->str(); return e;} if(is_url_like(token)){e.type=IocType::url; e.value=normalize_url(percent_decode(token)); return e;} if(is_hash_like(token)){e.type=IocType::hash; e.value=lower(token); return e;} std::string dom=normalize_domain(token); if(is_domain_name(dom)){e.type=IocType::domain; e.value=dom; return e;} e.type=IocType::unknown; e.value=token; d.warn("ioc.unrecognized","IOC value is not an IP, CIDR, domain, URL, or known hash length",line_no); return e;}
Result<IocSet> parse_ioc_text(const std::string& text){Diagnostics d; IocSet set; std::set<std::string> seen; auto lines=split_lines(text); for(std::size_t i=0;i<lines.size();++i){auto e=normalize_ioc_line(lines[i],d,i+1); if(e.value.empty())continue; std::string key=ioc_type_name(e.type)+":"+e.value+":"+(e.allow?"allow":"block"); if(!seen.insert(key).second){set.duplicates.push_back(key); d.warn("ioc.duplicate","duplicate IOC "+key,i+1);} set.entries.push_back(e);} return {set,d};}
static bool domain_matches(const std::string& indicator,const std::string& observed){auto i=normalize_domain(indicator),o=normalize_domain(observed); return o==i||ends_with(o,"."+i);} static std::string host_from_url(const std::string& url){auto p=url.find("://"); std::string rest=p==std::string::npos?url:url.substr(p+3); auto slash=rest.find('/'); return normalize_domain(rest.substr(0,slash));}
std::vector<IocMatch> match_packet_metadata(const IocSet& set,const std::vector<packet::PacketMetadata>& packets){std::vector<IocMatch> out; for(const auto& p:packets){for(const auto& e:set.entries){if(e.allow)continue; if(e.type==IocType::ip){if(p.src_ip&&p.src_ip->str()==e.value)out.push_back({e,"src_ip",e.value,p.summary()}); if(p.dst_ip&&p.dst_ip->str()==e.value)out.push_back({e,"dst_ip",e.value,p.summary()});} else if(e.type==IocType::cidr){auto c=parse_cidr(e.value); if(c&&p.src_ip&&c->contains(*p.src_ip))out.push_back({e,"src_cidr",p.src_ip->str(),p.summary()}); if(c&&p.dst_ip&&c->contains(*p.dst_ip))out.push_back({e,"dst_cidr",p.dst_ip->str(),p.summary()});} else if(e.type==IocType::domain){for(const auto& n:p.dns_names) if(domain_matches(e.value,n)) out.push_back({e,"dns",n,p.summary()});} else if(e.type==IocType::url){std::string host=host_from_url(e.value); for(const auto& n:p.dns_names) if(domain_matches(host,n)) out.push_back({e,"url_host",n,p.summary()});}}} return out;}
std::string summarize_iocs(const IocSet& set){std::map<std::string,int> counts; for(auto& e:set.entries)counts[ioc_type_name(e.type)]++; std::ostringstream o; o<<"entries="<<set.entries.size()<<" duplicates="<<set.duplicates.size(); for(auto& kv:counts)o<<" "<<kv.first<<"="<<kv.second; return o.str();} std::string summarize_matches(const std::vector<IocMatch>& matches){std::ostringstream o; for(auto& m:matches)o<<ioc_type_name(m.entry.type)<<" "<<m.entry.value<<" matched "<<m.field<<"="<<m.observed<<" in "<<m.packet_summary<<"\n"; return o.str();}
}
