#include "packet/packet.hpp"
#include "core/strings.hpp"
#include <iomanip>
#include <map>
#include <sstream>
namespace guardsight::packet {
using namespace guardsight::core;
static std::string mac(ByteView b){std::ostringstream o; o<<std::hex<<std::setfill('0'); for(std::size_t i=0;i<6&&i<b.size();++i){if(i)o<<":"; o<<std::setw(2)<<int(b[i]);} return o.str();}
std::string PacketMetadata::summary() const{std::ostringstream o; o<<timestamp.iso8601()<<" "; if(src_ip&&dst_ip)o<<src_ip->str()<<":"<<src_port<<" -> "<<dst_ip->str()<<":"<<dst_port; else o<<src_mac<<" -> "<<dst_mac; if(!protocol.empty())o<<" "<<protocol; if(!dns_names.empty())o<<" dns="<<join(dns_names,","); if(!notices.empty())o<<" notices="<<join(notices,"|"); return o.str();}
Result<EthernetFrame> parse_ethernet(ByteView bytes){Diagnostics d; if(bytes.size()<14){d.error("ethernet.truncated","Ethernet frame shorter than 14 bytes"); return d;} EthernetFrame f; f.dst_mac=mac(bytes.slice(0,6)); f.src_mac=mac(bytes.slice(6,6)); f.ether_type=read_u16_be(bytes.data()+12); std::size_t off=14; if(f.ether_type==0x8100&&bytes.size()>=18){f.ether_type=read_u16_be(bytes.data()+16); off=18;} f.payload=bytes.slice(off,bytes.size()-off); if(f.ether_type!=0x0800&&f.ether_type!=0x86dd&&f.ether_type!=0x0806)d.warn("ethernet.ethertype","uncommon EtherType "+std::to_string(f.ether_type)); return {f,d};}
Result<IPv4Packet> parse_ipv4_packet(ByteView bytes){Diagnostics d; if(bytes.size()<20){d.error("ipv4.truncated","IPv4 packet shorter than base header"); return d;} uint8_t ver_ihl=bytes[0]; uint8_t ver=ver_ihl>>4, ihl=ver_ihl&15; if(ver!=4)d.error("ipv4.version","packet is not IPv4"); if(ihl<5)d.error("ipv4.ihl","header length is smaller than 20 bytes"); std::size_t hlen=std::size_t(ihl)*4; if(bytes.size()<hlen){d.error("ipv4.options.truncated","IPv4 options exceed available bytes"); return d;} uint16_t total=read_u16_be(bytes.data()+2); if(total<hlen)d.error("ipv4.length","total length smaller than header length"); if(total>bytes.size()){d.warn("ipv4.capture.truncated","captured bytes shorter than total length"); total=uint16_t(bytes.size());} IPv4Packet p; p.ttl=bytes[8]; p.protocol=bytes[9]; p.id=read_u16_be(bytes.data()+4); p.flags_fragment=read_u16_be(bytes.data()+6); p.src.value=read_u32_be(bytes.data()+12); p.dst.value=read_u32_be(bytes.data()+16); std::vector<uint8_t> header=bytes.slice(0,hlen).to_vector(); header[10]=0; header[11]=0; uint16_t calc=internet_checksum(ByteView(header)); uint16_t got=read_u16_be(bytes.data()+10); p.checksum_valid=calc==got||got==0; if(!p.checksum_valid)d.warn("ipv4.checksum","IPv4 header checksum mismatch"); if(p.ttl==0)d.warn("ipv4.ttl","TTL is zero"); p.payload=bytes.slice(hlen,total>hlen?total-hlen:0); return {p,d};}
Result<TransportInfo> parse_transport(const IPv4Packet& ip){Diagnostics d; TransportInfo t; t.protocol=protocol_name(ip.protocol); if(ip.protocol==6){if(ip.payload.size()<20){d.error("tcp.truncated","TCP header shorter than 20 bytes"); return d;} t.src_port=read_u16_be(ip.payload.data()); t.dst_port=read_u16_be(ip.payload.data()+2); uint8_t off=(ip.payload[12]>>4)*4; if(off<20||off>ip.payload.size()){d.error("tcp.offset","TCP data offset outside packet"); return d;} t.tcp_flags=ip.payload[13]; t.payload=ip.payload.slice(off,ip.payload.size()-off);} else if(ip.protocol==17){if(ip.payload.size()<8){d.error("udp.truncated","UDP header shorter than 8 bytes"); return d;} t.src_port=read_u16_be(ip.payload.data()); t.dst_port=read_u16_be(ip.payload.data()+2); uint16_t len=read_u16_be(ip.payload.data()+4); if(len<8)d.error("udp.length","UDP length shorter than header"); std::size_t plen=len>=8?std::min<std::size_t>(len-8,ip.payload.size()-8):0; t.payload=ip.payload.slice(8,plen);} return {t,d};}
static bool read_name(ByteView b,std::size_t& off,std::string& name,int depth=0){if(depth>12)return false; std::vector<std::string> labels; std::size_t p=off; bool jumped=false; while(p<b.size()){uint8_t len=b[p++]; if(len==0){if(!jumped)off=p; name=join(labels,"."); return true;} if((len&0xc0)==0xc0){if(p>=b.size())return false; uint16_t ptr=((len&0x3f)<<8)|b[p++]; if(ptr>=b.size())return false; if(!jumped)off=p; p=ptr; jumped=true; if(++depth>12)return false; continue;} if(len>63||p+len>b.size())return false; std::string label(reinterpret_cast<const char*>(b.data()+p),reinterpret_cast<const char*>(b.data()+p+len)); labels.push_back(label); p+=len;} return false;}
Result<DnsMessage> parse_dns(ByteView bytes){Diagnostics d; if(bytes.size()<12){d.error("dns.truncated","DNS message shorter than header"); return d;} DnsMessage m; m.id=read_u16_be(bytes.data()); uint16_t flags=read_u16_be(bytes.data()+2); m.response=(flags&0x8000)!=0; m.rcode=uint8_t(flags&15); uint16_t qd=read_u16_be(bytes.data()+4), an=read_u16_be(bytes.data()+6); std::size_t off=12; for(uint16_t i=0;i<qd&&i<64;++i){DnsQuestion q; if(!read_name(bytes,off,q.name)){d.error("dns.qname","invalid compressed question name",off); return d;} if(off+4>bytes.size()){d.error("dns.question.truncated","question fields truncated",off); return d;} q.type=read_u16_be(bytes.data()+off); q.klass=read_u16_be(bytes.data()+off+2); off+=4; m.questions.push_back(q);} for(uint16_t i=0;i<an&&i<128;++i){DnsRecord r; if(!read_name(bytes,off,r.name)){d.error("dns.rrname","invalid answer name",off); return d;} if(off+10>bytes.size()){d.error("dns.rr.truncated","answer header truncated",off); return d;} r.type=read_u16_be(bytes.data()+off); r.klass=read_u16_be(bytes.data()+off+2); r.ttl=read_u32_be(bytes.data()+off+4); uint16_t rdlen=read_u16_be(bytes.data()+off+8); off+=10; if(off+rdlen>bytes.size()){d.error("dns.rdata.truncated","answer data truncated",off); return d;} if(r.type==1&&rdlen==4){IPv4Address a{read_u32_be(bytes.data()+off)}; r.data=a.str();} else if((r.type==5||r.type==2||r.type==12)&&rdlen>0){std::size_t roff=off; std::string n; if(read_name(bytes,roff,n))r.data=n;} else r.data=hex_encode(bytes.slice(off,rdlen)); off+=rdlen; m.answers.push_back(r);} return {m,d};}
Result<PcapFile> parse_pcap(ByteView bytes){Diagnostics d; ByteReader r(bytes,&d); uint32_t magic=0; if(!r.read_u32_le(magic)) return d; bool le=true; bool ns=false; if(magic==0xa1b2c3d4){le=false;} else if(magic==0xd4c3b2a1){le=true;} else if(magic==0xa1b23c4d){le=false; ns=true;} else if(magic==0x4d3cb2a1){le=true; ns=true;} else {d.error("pcap.magic","unrecognized PCAP magic"); return d;} auto ru16=[&](uint16_t& v){return le?r.read_u16_le(v):r.read_u16_be(v);}; auto ru32=[&](uint32_t& v){return le?r.read_u32_le(v):r.read_u32_be(v);}; uint16_t major=0,minor=0; uint32_t tmp=0; PcapFile p; ru16(major); ru16(minor); ru32(tmp); ru32(tmp); ru32(p.snaplen); ru32(p.network); p.nanosecond=ns; if(major!=2)d.warn("pcap.version","unexpected PCAP major version"); while(r.remaining()>=16&&p.packets.size()<100000){uint32_t sec=0,frac=0,cap=0,orig=0; ru32(sec); ru32(frac); ru32(cap); ru32(orig); if(cap>p.snaplen&&p.snaplen)d.warn("pcap.snaplen","captured length exceeds snaplen",r.offset()); if(cap>r.remaining()){d.error("pcap.packet.truncated","packet record exceeds file size",r.offset()); break;} ByteView payload; r.read_bytes(cap,payload); PcapPacket pkt; pkt.timestamp={int64_t(sec), int32_t(ns?frac/1000:frac)}; pkt.bytes=payload.to_vector(); pkt.original_length=orig; p.packets.push_back(std::move(pkt));} if(r.remaining()>0&&r.remaining()<16)d.warn("pcap.trailing","trailing partial record header",r.offset()); return {p,d};}
Result<std::vector<PacketMetadata>> extract_metadata(const PcapFile& pcap){Diagnostics d; std::vector<PacketMetadata> out; for(const auto& rec:pcap.packets){PacketMetadata m; m.timestamp=rec.timestamp; m.wire_length=rec.original_length; auto eth=parse_ethernet(ByteView(rec.bytes)); d.items().size(); for(auto& x:eth.diagnostics().items()) d.add(x.severity,x.code,x.message,x.offset); if(!eth) {out.push_back(m); continue;} auto e=eth.value(); m.src_mac=e.src_mac; m.dst_mac=e.dst_mac; if(e.ether_type==0x0800){auto ipr=parse_ipv4_packet(e.payload); for(auto& x:ipr.diagnostics().items()) d.add(x.severity,x.code,x.message,x.offset); if(ipr){auto ip=ipr.value(); m.src_ip=ip.src; m.dst_ip=ip.dst; auto tr=parse_transport(ip); for(auto& x:tr.diagnostics().items()) d.add(x.severity,x.code,x.message,x.offset); if(tr){auto ti=tr.value(); m.protocol=ti.protocol; m.src_port=ti.src_port; m.dst_port=ti.dst_port; if((ti.src_port==53||ti.dst_port==53)&&!ti.payload.empty()){auto dns=parse_dns(ti.payload); for(auto& x:dns.diagnostics().items()) d.add(x.severity,x.code,x.message,x.offset); if(dns){for(auto& q:dns.value().questions)m.dns_names.push_back(q.name); for(auto& a:dns.value().answers) if(!a.name.empty())m.dns_names.push_back(a.name);}}}}} out.push_back(m);} return {out,d};}
std::string summarize_packets(const std::vector<PacketMetadata>& packets){std::ostringstream o; for(const auto& p:packets)o<<p.summary()<<'\n'; return o.str();}
}
