#include "policy/policy.hpp"
#include "core/strings.hpp"
#include <algorithm>
#include <set>
#include <sstream>
namespace guardsight::policy {
using namespace guardsight::core;
static FirewallRule parse_iptables(const std::string& line,Diagnostics& d,std::size_t ln){FirewallRule r; r.raw=line; r.family="ipv4"; auto t=split(collapse_spaces(line),' '); for(std::size_t i=0;i<t.size();++i){std::string x=t[i]; if((x=="-A"||x=="-I")&&i+1<t.size())r.chain=t[++i]; else if((x=="-p"||x=="--protocol")&&i+1<t.size())r.protocol=lower(t[++i]); else if((x=="-s"||x=="--source")&&i+1<t.size())r.source=t[++i]; else if((x=="-d"||x=="--destination")&&i+1<t.size())r.destination=t[++i]; else if((x=="--dport"||x=="--destination-port")&&i+1<t.size()){try{int p=std::stoi(t[++i]); if(p>=0&&p<=65535){r.dport=uint16_t(p); r.any_dport=false;}}catch(...){d.warn("policy.port","invalid destination port",ln);}} else if((x=="-j"||x=="--jump")&&i+1<t.size())r.action=upper(t[++i]);} if(r.chain.empty())d.warn("policy.chain","iptables rule missing chain",ln); if(r.action.empty())d.warn("policy.action","iptables rule missing action",ln); return r;}
static FirewallRule parse_nft(const std::string& line,Diagnostics& d,std::size_t ln){FirewallRule r; r.raw=line; r.family="inet"; auto t=split(collapse_spaces(line),' '); for(std::size_t i=0;i<t.size();++i){std::string x=lower(t[i]); if(x=="ip"||x=="ip6"||x=="inet")r.family=x; else if(x=="tcp"||x=="udp"||x=="icmp")r.protocol=x; else if(x=="dport"&&i+1<t.size()){try{int p=std::stoi(t[++i]); if(p>=0&&p<=65535){r.dport=uint16_t(p); r.any_dport=false;}}catch(...){d.warn("policy.nft.port","invalid nft dport",ln);}} else if(x=="saddr"&&i+1<t.size())r.source=t[++i]; else if(x=="daddr"&&i+1<t.size())r.destination=t[++i]; else if(x=="accept"||x=="drop"||x=="reject")r.action=upper(x); else if((x=="input"||x=="output"||x=="forward")&&r.chain.empty())r.chain=upper(x);} if(r.chain.empty())r.chain="NFT"; if(r.action.empty())d.warn("policy.nft.action","nft rule missing terminal action",ln); return r;}
Result<PolicyFile> parse_policy_text(const std::string& text){Diagnostics d; PolicyFile p; std::string section; auto lines=split_lines(text); for(std::size_t i=0;i<lines.size();++i){auto raw=trim(remove_comment(lines[i])); if(raw.empty())continue; if(raw.front()=='['&&raw.back()==']'){section=lower(raw.substr(1,raw.size()-2)); continue;} if(starts_with(raw,"-A ")||starts_with(raw,"-I ")||starts_with(raw,"iptables ")){std::string line=starts_with(raw,"iptables ")?raw.substr(9):raw; p.rules.push_back(parse_iptables(line,d,i+1)); continue;} std::string low=lower(raw); if(low.find(" dport ")!=std::string::npos||starts_with(low,"add rule")||low.find(" accept")!=std::string::npos||low.find(" drop")!=std::string::npos){p.rules.push_back(parse_nft(raw,d,i+1)); continue;} if(raw.find('{')!=std::string::npos||raw.find('}')!=std::string::npos||raw.find(':')!=std::string::npos){auto pos=raw.find(':'); if(pos!=std::string::npos)p.settings[lower(trim(raw.substr(0,pos)))]=strip_quotes(trim(raw.substr(pos+1))); continue;} auto pos=raw.find('='); if(pos!=std::string::npos){std::string key=section.empty()?lower(trim(raw.substr(0,pos))):section+"."+lower(trim(raw.substr(0,pos))); p.settings[key]=strip_quotes(trim(raw.substr(pos+1))); continue;} d.warn("policy.unknown","unrecognized policy line",i+1);} return {p,d};}
std::string normalize_firewall_rule(const FirewallRule& r){std::ostringstream o; o<<upper(r.chain)<<' '<<upper(r.action)<<' '<<lower(r.protocol)<<' '<<r.source<<" -> "<<r.destination; if(!r.any_dport)o<<":"<<r.dport; return o.str();} static bool covers_addr(const std::string& a,const std::string& b){if(lower(a)=="any")return true; if(a==b)return true; auto ca=parse_cidr(a), cb=parse_cidr(b); if(ca&&cb)return ca->contains(cb->network); auto ip=parse_ipv4(b); return ca&&ip&&ca->contains(*ip);} static bool covers(const FirewallRule& a,const FirewallRule& b){return (lower(a.protocol)=="any"||lower(a.protocol)==lower(b.protocol))&&covers_addr(a.source,b.source)&&covers_addr(a.destination,b.destination)&&(a.any_dport||( !b.any_dport&&a.dport==b.dport));}
std::vector<PolicyFinding> analyze_policy(const PolicyFile& p){std::vector<PolicyFinding> f; std::set<std::string> seen; for(std::size_t i=0;i<p.rules.size();++i){auto n=normalize_firewall_rule(p.rules[i]); if(!seen.insert(n).second)f.push_back({"medium","duplicate firewall rule: "+n,i+1}); if(p.rules[i].action=="ACCEPT"&&lower(p.rules[i].protocol)=="tcp"&&p.rules[i].any_dport&&lower(p.rules[i].destination)=="any")f.push_back({"high","broad TCP accept rule without destination port",i+1}); if((p.rules[i].action=="DROP"||p.rules[i].action=="REJECT")&&lower(p.rules[i].chain)=="output")f.push_back({"info","outbound deny rule may affect update and telemetry flows",i+1}); for(std::size_t j=0;j<i;++j){if(p.rules[j].action!=p.rules[i].action&&covers(p.rules[j],p.rules[i])){f.push_back({"medium","rule shadowed by earlier "+p.rules[j].action+" rule",i+1}); break;}}} if(!p.settings.count("default_policy")&&!p.settings.count("firewall.default_policy"))f.push_back({"low","default policy setting not declared",0}); return f;}
std::string summarize_policy(const PolicyFile& p,const std::vector<PolicyFinding>& f){std::map<std::string,int> chains,actions; for(auto& r:p.rules){chains[r.chain]++; actions[r.action]++;} std::ostringstream o; o<<"rules="<<p.rules.size()<<" settings="<<p.settings.size()<<" findings="<<f.size(); for(auto& c:chains)o<<" chain."<<c.first<<"="<<c.second; for(auto& a:actions)o<<" action."<<a.first<<"="<<a.second; for(auto& x:f)o<<"\n"<<x.severity<<": "<<x.message; return o.str();}
}
