#include "core/bytes.hpp"
#include <algorithm>
#include <iomanip>
#include <sstream>
namespace guardsight::core {
ByteView ByteView::slice(std::size_t o,std::size_t n) const{if(o>size_) return {}; return {data_+o,std::min(n,size_-o)};} std::vector<uint8_t> ByteView::to_vector() const{return data_?std::vector<uint8_t>(data_,data_+size_):std::vector<uint8_t>{};} std::string ByteView::ascii_lossy() const{std::string r; r.reserve(size_); for(std::size_t i=0;i<size_;++i){uint8_t c=data_[i]; r.push_back(c>=32&&c<=126?char(c):'.');} return r;}
void ByteReader::fail(std::size_t n){if(diagnostics_) diagnostics_->error("truncated","input ended while reading "+std::to_string(n)+" byte(s)",offset_);} bool ByteReader::seek(std::size_t o){if(o>view_.size()){fail(o-view_.size()); return false;} offset_=o; return true;} bool ByteReader::skip(std::size_t n){if(!can_read(n)){fail(n); return false;} offset_+=n; return true;} bool ByteReader::read_u8(uint8_t& v){if(!can_read(1)){fail(1); return false;} v=view_[offset_++]; return true;} bool ByteReader::read_u16_be(uint16_t& v){if(!can_read(2)){fail(2); return false;} v=core::read_u16_be(view_.data()+offset_); offset_+=2; return true;} bool ByteReader::read_u16_le(uint16_t& v){if(!can_read(2)){fail(2); return false;} v=core::read_u16_le(view_.data()+offset_); offset_+=2; return true;} bool ByteReader::read_u32_be(uint32_t& v){if(!can_read(4)){fail(4); return false;} v=core::read_u32_be(view_.data()+offset_); offset_+=4; return true;} bool ByteReader::read_u32_le(uint32_t& v){if(!can_read(4)){fail(4); return false;} v=core::read_u32_le(view_.data()+offset_); offset_+=4; return true;} bool ByteReader::read_i32_le(int32_t& v){uint32_t r=0; if(!read_u32_le(r)) return false; v=static_cast<int32_t>(r); return true;} bool ByteReader::read_bytes(std::size_t n,ByteView& out){if(!can_read(n)){fail(n); return false;} out=view_.slice(offset_,n); offset_+=n; return true;}
uint16_t read_u16_be(const uint8_t* d){return uint16_t((uint16_t(d[0])<<8)|d[1]);} uint16_t read_u16_le(const uint8_t* d){return uint16_t((uint16_t(d[1])<<8)|d[0]);} uint32_t read_u32_be(const uint8_t* d){return (uint32_t(d[0])<<24)|(uint32_t(d[1])<<16)|(uint32_t(d[2])<<8)|d[3];} uint32_t read_u32_le(const uint8_t* d){return (uint32_t(d[3])<<24)|(uint32_t(d[2])<<16)|(uint32_t(d[1])<<8)|d[0];}
uint16_t internet_checksum(ByteView v){uint32_t sum=0; std::size_t i=0; while(i+1<v.size()){sum+=read_u16_be(v.data()+i); i+=2;} if(i<v.size()) sum+=uint16_t(v[i])<<8; while(sum>>16) sum=(sum&0xffffu)+(sum>>16); return uint16_t(~sum);} std::string hex_encode(ByteView v,bool spaced){std::ostringstream o; o<<std::hex<<std::setfill('0'); for(std::size_t i=0;i<v.size();++i){if(spaced&&i)o<<' '; o<<std::setw(2)<<int(v[i]);} return o.str();} static int hv(char c){if(c>='0'&&c<='9')return c-'0'; if(c>='a'&&c<='f')return c-'a'+10; if(c>='A'&&c<='F')return c-'A'+10; return -1;} std::vector<uint8_t> hex_decode_relaxed(const std::string& s){std::vector<uint8_t> n,b; for(char c:s){int v=hv(c); if(v>=0)n.push_back(uint8_t(v));} for(std::size_t i=0;i+1<n.size();i+=2)b.push_back(uint8_t((n[i]<<4)|n[i+1])); return b;}
}
