#include "core/net.hpp"
#include "core/strings.hpp"
#include <algorithm>
#include <cctype>
#include <map>
#include <sstream>
namespace guardsight::core {
std::string IPv4Address::str() const{std::ostringstream o; o<<((value>>24)&255)<<'.'<<((value>>16)&255)<<'.'<<((value>>8)&255)<<'.'<<(value&255); return o.str();} bool IPv4Address::is_private() const{auto a=uint8_t(value>>24),b=uint8_t(value>>16); return a==10||(a==172&&b>=16&&b<=31)||(a==192&&b==168);} bool IPv4Address::is_multicast() const{auto a=uint8_t(value>>24); return a>=224&&a<=239;} bool IPv4Address::is_loopback() const{return uint8_t(value>>24)==127;} bool CidrBlock::contains(IPv4Address a) const{if(prefix==0)return true; uint32_t mask=prefix==32?0xffffffffu:(0xffffffffu<<(32-prefix)); return (network.value&mask)==(a.value&mask);} std::string CidrBlock::str() const{return network.str()+"/"+std::to_string(prefix);} std::optional<IPv4Address> parse_ipv4(const std::string& t){auto parts=split(trim(t),'.',true); if(parts.size()!=4)return std::nullopt; uint32_t v=0; for(auto& p:parts){if(!is_decimal(p)||p.size()>3)return std::nullopt; int n=std::stoi(p); if(n<0||n>255)return std::nullopt; v=(v<<8)|uint32_t(n);} return IPv4Address{v};} std::optional<CidrBlock> parse_cidr(const std::string& t){auto pos=t.find('/'); if(pos==std::string::npos){auto ip=parse_ipv4(t); if(!ip)return std::nullopt; return CidrBlock{*ip,32};} auto ip=parse_ipv4(t.substr(0,pos)); auto ps=trim(t.substr(pos+1)); if(!ip||!is_decimal(ps))return std::nullopt; int p=std::stoi(ps); if(p<0||p>32)return std::nullopt; CidrBlock b{*ip,uint8_t(p)}; uint32_t mask=p==0?0:(p==32?0xffffffffu:(0xffffffffu<<(32-p))); b.network.value&=mask; return b;} bool is_domain_label(const std::string& l){if(l.empty()||l.size()>63||l.front()=='-'||l.back()=='-')return false; for(unsigned char c:l) if(!std::isalnum(c)&&c!='-')return false; return true;} bool is_domain_name(const std::string& d){std::string n=normalize_domain(d); if(n.size()>253||n.find('.')==std::string::npos)return false; for(auto& l:split(n,'.',true)) if(!is_domain_label(l)) return false; return true;} bool is_url_like(const std::string& v){auto s=lower(trim(v)); return starts_with(s,"http://")||starts_with(s,"https://")||starts_with(s,"ftp://");} bool is_hash_like(const std::string& v){auto s=lower(trim(v)); if(!is_hex_string(s))return false; return s.size()==32||s.size()==40||s.size()==56||s.size()==64||s.size()==96||s.size()==128;}
std::string protocol_name(uint8_t p){switch(p){case 1:return "icmp";case 6:return "tcp";case 17:return "udp";case 47:return "gre";case 50:return "esp";case 51:return "ah";case 58:return "icmpv6";default:return "ipproto-"+std::to_string(p);}} std::string service_name(uint16_t port,uint8_t proto){static const std::map<uint16_t,std::string> tcp={{20,"ftp-data"},{21,"ftp"},{22,"ssh"},{23,"telnet"},{25,"smtp"},{53,"dns"},{80,"http"},{110,"pop3"},{123,"ntp"},{135,"msrpc"},{137,"netbios-ns"},{138,"netbios-dgm"},{139,"netbios-ssn"},{143,"imap"},{161,"snmp"},{389,"ldap"},{443,"https"},{445,"smb"},{465,"smtps"},{514,"syslog"},{587,"smtp-submit"},{636,"ldaps"},{993,"imaps"},{995,"pop3s"},{1433,"mssql"},{1521,"oracle"},{3306,"mysql"},{3389,"rdp"},{5432,"postgres"},{5900,"vnc"},{6379,"redis"},{8080,"http-alt"},{8443,"https-alt"},{9200,"elasticsearch"},{9300,"elasticsearch-node"},{11211,"memcached"},{27017,"mongodb"}}; static const std::map<uint16_t,std::string> udp={{53,"dns"},{67,"dhcp-server"},{68,"dhcp-client"},{69,"tftp"},{123,"ntp"},{137,"netbios-ns"},{138,"netbios-dgm"},{161,"snmp"},{162,"snmptrap"},{500,"ike"},{514,"syslog"},{520,"rip"},{1900,"ssdp"},{4500,"ipsec-nat-t"},{5353,"mdns"},{11211,"memcached"}}; auto& tab=proto==17?udp:tcp; auto it=tab.find(port); return it==tab.end()?std::to_string(port):it->second;} std::string dns_type_name(uint16_t t){switch(t){case 1:return "A";case 2:return "NS";case 5:return "CNAME";case 6:return "SOA";case 10:return "NULL";case 12:return "PTR";case 15:return "MX";case 16:return "TXT";case 28:return "AAAA";case 33:return "SRV";case 41:return "OPT";case 43:return "DS";case 46:return "RRSIG";case 47:return "NSEC";case 48:return "DNSKEY";case 65:return "HTTPS";case 255:return "ANY";default:return "TYPE"+std::to_string(t);}} std::string dns_class_name(uint16_t c){switch(c){case 1:return "IN";case 3:return "CH";case 4:return "HS";case 255:return "ANY";default:return "CLASS"+std::to_string(c);}} std::vector<std::string> suspicious_tlds(){return {"zip","mov","top","xyz","icu","click","country","gq","tk","ml","cf","ga","work","support","review","kim","rest","quest","cam"};}
}
