#include "core/strings.hpp"
#include <algorithm>
#include <cctype>
#include <sstream>
namespace guardsight::core {
std::string trim(std::string v){auto ns=[](unsigned char c){return !std::isspace(c);}; v.erase(v.begin(),std::find_if(v.begin(),v.end(),ns)); v.erase(std::find_if(v.rbegin(),v.rend(),ns).base(),v.end()); return v;} std::string lower(std::string v){std::transform(v.begin(),v.end(),v.begin(),[](unsigned char c){return char(std::tolower(c));}); return v;} std::string upper(std::string v){std::transform(v.begin(),v.end(),v.begin(),[](unsigned char c){return char(std::toupper(c));}); return v;} bool starts_with(const std::string& v,const std::string& p){return v.size()>=p.size()&&std::equal(p.begin(),p.end(),v.begin());} bool ends_with(const std::string& v,const std::string& s){return v.size()>=s.size()&&std::equal(s.rbegin(),s.rend(),v.rbegin());}
std::vector<std::string> split(const std::string& v,char d,bool keep){std::vector<std::string> out; std::string cur; std::istringstream in(v); while(std::getline(in,cur,d)){if(keep||!cur.empty()) out.push_back(cur);} if(keep&&!v.empty()&&v.back()==d) out.emplace_back(); return out;} std::vector<std::string> split_lines(const std::string& v){std::vector<std::string> out; std::string cur; std::istringstream in(v); while(std::getline(in,cur)){if(!cur.empty()&&cur.back()=='\r')cur.pop_back(); out.push_back(cur);} return out;} std::string join(const std::vector<std::string>& v,const std::string& d){std::ostringstream o; for(std::size_t i=0;i<v.size();++i){if(i)o<<d; o<<v[i];} return o.str();}
std::string collapse_spaces(const std::string& v){std::string o; bool ps=false; for(unsigned char c:v){if(std::isspace(c)){if(!ps)o.push_back(' '); ps=true;}else{o.push_back(char(c)); ps=false;}} return trim(o);} bool is_decimal(const std::string& v){if(v.empty())return false; for(unsigned char c:v) if(!std::isdigit(c)) return false; return true;} bool is_hex_string(const std::string& v){if(v.empty())return false; for(unsigned char c:v) if(!std::isxdigit(c)) return false; return true;} bool is_printable_ascii(const std::string& v){for(unsigned char c:v) if(c<32||c>126) return false; return true;} std::string strip_quotes(const std::string& v){std::string s=trim(v); if(s.size()>=2&&((s.front()=='"'&&s.back()=='"')||(s.front()=='\''&&s.back()=='\''))) return s.substr(1,s.size()-2); return s;}
std::string remove_comment(const std::string& line){bool q=false; char qc=0; for(std::size_t i=0;i<line.size();++i){char c=line[i]; if((c=='"'||c=='\'')&&(i==0||line[i-1]!='\\')){if(!q){q=true;qc=c;}else if(qc==c)q=false;} if(!q&&c=='#') return line.substr(0,i);} return line;} std::map<std::string,std::string> parse_key_value_list(const std::string& text,char pd,char kd){std::map<std::string,std::string> m; for(auto& p:split(text,pd)){auto pos=p.find(kd); if(pos!=std::string::npos)m[lower(trim(p.substr(0,pos)))] = strip_quotes(trim(p.substr(pos+1)));} return m;} std::string escape_json(const std::string& v){std::string o; for(char c:v){switch(c){case '"':o+="\\\"";break;case '\\':o+="\\\\";break;case '\n':o+="\\n";break;case '\r':o+="\\r";break;case '\t':o+="\\t";break;default:o.push_back(c);}} return o;} std::string percent_decode(const std::string& v){auto hx=[](char c){if(c>='0'&&c<='9')return c-'0'; if(c>='a'&&c<='f')return c-'a'+10; if(c>='A'&&c<='F')return c-'A'+10; return -1;}; std::string o; for(std::size_t i=0;i<v.size();++i){if(v[i]=='%'&&i+2<v.size()){int h=hx(v[i+1]),l=hx(v[i+2]); if(h>=0&&l>=0){o.push_back(char((h<<4)|l)); i+=2; continue;}} o.push_back(v[i]);} return o;} std::string normalize_domain(const std::string& v){std::string s=lower(trim(v)); while(!s.empty()&&s.back()=='.')s.pop_back(); return s;} std::string normalize_url(const std::string& v){std::string s=trim(v); auto p=s.find("://"); if(p==std::string::npos)return s; std::string scheme=lower(s.substr(0,p)); std::string rest=s.substr(p+3); auto slash=rest.find('/'); if(slash==std::string::npos)return scheme+"://"+lower(rest); return scheme+"://"+lower(rest.substr(0,slash))+rest.substr(slash);}
}
